name: Build IPMS Frontend

on:
  workflow_dispatch:

jobs:
  build-frontend:
    runs-on: self-hosted

    steps:

      - name: Checkout Frontend
        uses: actions/checkout@v5

      - name: Check Node Version
        shell: powershell
        run: |
          node --version
          npm --version

      - name: Install Dependencies
        shell: powershell
        run: |
          npm ci --legacy-peer-deps

      - name: Build Angular Application
        shell: powershell
        run: |
          npm run build

      - name: Verify Build
        shell: powershell
        run: |
          Write-Host "Build completed."
          Get-ChildItem -Path .\dist -Recurse | Select-Object FullName

      - name: Test IIS Folder Permission
        shell: powershell
        run: |
          $testFile = "C:\inetpub\wwwroot\ipms\github-runner-test.txt"

          "GitHub Runner deployment permission test" |
            Out-File -FilePath $testFile -Encoding utf8

          Write-Host "Test file created successfully:"
          Get-Item $testFile

          Remove-Item $testFile -Force

          Write-Host "Test file removed successfully."